# Generated by Django 3.0.8 on 2020-07-31 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=30)),
                ('Q1', models.CharField(max_length=60)),
                ('Q2', models.CharField(max_length=60)),
                ('Q3', models.CharField(max_length=60)),
                ('Q4', models.CharField(max_length=60)),
                ('Q5', models.CharField(max_length=60)),
                ('Q1pic', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q2pic', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q3pic', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q4pic', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q5pic', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
