# Generated by Django 3.0.8 on 2020-07-31 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='madeby',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
