# Generated by Django 3.0.8 on 2020-07-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_item_madeby'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madeby', models.CharField(max_length=30, null=True)),
                ('Q1ans', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q2ans', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q3ans', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q4ans', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
                ('Q5ans', models.CharField(choices=[('1', '아리랑'), ('2', '아리랑'), ('3', '아리랑'), ('4', '아리랑'), ('5', '아리랑')], max_length=2)),
            ],
        ),
    ]
